version: '3.8'

networks:
  network-zabbix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8
    networks:
      network-zabbix:
          ipv4_address: 172.20.0.3
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=enzo123
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    networks:
      network-zabbix:
        ipv4_address: 172.20.0.4
    restart: unless-stopped
    ports:
      - '10051:10051'
    volumes:
      # - './sslCert:/var/lib/zabbix/ssl/certs'
      # - './sslKeys:/var/lib/zabbix/ssl/keys'
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-server-config:/etc/zabbix
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_SERVER_HOST=mariadb
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=enzo123
      - ZBX_LISTENPORTS=10051
    depends_on:
      - mariadb

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    networks:
      network-zabbix:
          ipv4_address: 172.20.0.5
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:8443'
    volumes: 
      - '/etc/httpd/ssl/:/etc/ssl/apache2'
    environment:
      - DB_SERVER_HOST=mariadb
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=enzo123
      - ZBX_SERVER_HOST=172.20.0.4
      - ZBX_SERVER_PORT=10051
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mariadb

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      network-zabbix:
          ipv4_address: 172.20.0.6
    restart: unless-stopped
    ports:
      - '3000:3000'
    user: root
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mariadb
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    user: root
    networks:
      network-zabbix:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    privileged: true
    ports:
      - '10050:10050'
    volumes:
      - ./var/run:/var/run
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.20.0.4
      - ZBX_SERVER_PORT=10051
volumes:
  grafana-storage: {}
  mariadb: {} 
  zabbix-server-data: {}
  zabbix-server-config: {}

